# Generated by Django 5.2.5 on 2025-09-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentcommentattachment",
            name="comment",
        ),
        migrations.DeleteModel(
            name="DepartmentComment",
        ),
        migrations.DeleteModel(
            name="DepartmentCommentAttachment",
        ),
    ]
