# Generated by Django 5.2.5 on 2025-08-28 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="departmentsection",
            name="unique_section_type_per_department",
        ),
        migrations.AddConstraint(
            model_name="departmentsection",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_section_type_per_department"
            ),
        ),
    ]
