# Generated by Django 5.2.5 on 2025-09-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_remove_departmentcommentattachment_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("chief", "Chief"),
                    ("assistant", "Assistant"),
                    ("secretary", "Secretary"),
                    ("team_member", "Team Member"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
    ]
