# Generated by Django 5.2.5 on 2025-09-29 06:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("CHIEF_INFO", "Chief Info"),
                            ("TEAM_INFO", "Team Info"),
                            ("ASSISTANT_INFO", "Assistant Info"),
                            ("SECRETARY_INFO", "Secretary Info"),
                            ("INTERACTIONS", "Interactions"),
                            ("MEDIA", "Media"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content_draft", models.JSONField(blank=True, default=dict)),
                ("content_published", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("members", "All Members"),
                            ("role_scoped", "Role Scoped"),
                        ],
                        default="public",
                        max_length=15,
                    ),
                ),
                ("visible_for_roles", models.JSONField(blank=True, default=list)),
                ("allow_edit_roles", models.JSONField(blank=True, default=list)),
                ("allow_publish_roles", models.JSONField(blank=True, default=list)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="department.department",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="media_assets/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "mov",
                                    "avi",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=10
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="department.department",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to="sections.departmentsection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SectionPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("chief", "Chief"),
                            ("assistant", "Assistant"),
                            ("secretary", "Secretary"),
                            ("team_member", "Team Member"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_view", models.BooleanField()),
                ("can_edit", models.BooleanField()),
                ("can_publish", models.BooleanField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="sections.departmentsection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VersionedSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("version", models.PositiveIntegerField()),
                ("content", models.JSONField(default=dict)),
                ("published_at", models.DateTimeField(auto_now=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versioned_sections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="sections.departmentsection",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "-version"],
            },
        ),
        migrations.AddConstraint(
            model_name="departmentsection",
            constraint=models.UniqueConstraint(
                fields=("department", "type"), name="unique_section_type_per_department"
            ),
        ),
        migrations.AddConstraint(
            model_name="versionedsection",
            constraint=models.UniqueConstraint(
                fields=("section", "version"), name="unique_section_version"
            ),
        ),
    ]
