# Generated by Django 5.2.5 on 2025-09-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionedsection",
            name="published_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
