# Generated by Django 5.2.5 on 2025-09-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0002_alter_versionedsection_published_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
