# Generated by Django 5.2.5 on 2026-05-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_remove_json_role_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionpermission',
            options={},
        ),
    ]
