# Generated by Django 5.2.5 on 2025-09-14 15:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
        ("department", "0002_remove_departmentcommentattachment_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admincommentattachment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="admincommentattachment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="admincommentattachment",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="admindepartmentcomment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="admindepartmentcomment",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="admindepartmentcomment",
            name="author_role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("chief", "Chief"),
                    ("assistant", "Assistant"),
                    ("secretary", "Secretary"),
                    ("team_member", "Team Member"),
                    ("viewer", "Viewer"),
                    ("rectorate", "Rectorate"),
                    ("clergy", "Clergy"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("payload", models.JSONField(blank=True, default=list)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditlogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deaprtment_auditlogs",
                        to="department.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
