# Generated by Django 5.2.5 on 2025-09-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_alter_admincommentattachment_options_and_more"),
        ("sections", "0002_alter_versionedsection_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="action",
            field=models.CharField(default="read_action", max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sections.departmentsection",
            ),
        ),
    ]
