# Generated by Django 5.2.5 on 2025-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_auditlog_action_auditlog_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
