# Generated by Django 5.2.5 on 2025-09-14 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0004_alter_auditlog_payload"),
        ("department", "0002_remove_departmentcommentattachment_comment_and_more"),
        ("sections", "0003_delete_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["department", "created_at"],
                name="adminapp_au_departm_37c24d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "created_at"], name="adminapp_au_actor_i_4d38ee_idx"
            ),
        ),
    ]
