# Generated by Django 5.2.5 on 2025-09-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0005_auditlog_adminapp_au_departm_37c24d_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admindepartmentcomment",
            name="author_role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("chief", "Chief"),
                    ("assistant", "Assistant"),
                    ("secretary", "Secretary"),
                    ("team_member", "Team Member"),
                    ("viewer", "Viewer"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
